version: "3.7"

x-buildargs: &build_args
  GIT_COMMIT: ${GIT_COMMIT:-'git-commit'}
  BUILD_VERSION: ${BUILD_VERSION:-'semver'}

services:

  api:
    image: ${CR_BASE:-ghcr.io/implex1v}/taal-as-a-service-api:${BUILD_VERSION:-latest}
    restart: unless-stopped
    ports:
      - 8080:8080
    build:
      context: .
      args:
        <<: *build_args
